function results = imfcElv(im)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------



% Replace the sample below with your code----------------------------------
im = imresize(im , [76 150]);
imOut = im;

results.imout = imOut;
results.imoutFlipped1 = flip(imOut,2);
results.imoutFlipped2 = flip(imOut,1);
results.imoutFlipped3 = flip(flip(imOut , 2),1);
%--------------------------------------------------------------------------

