function results = myimfcn(im)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------



% Replace the sample below with your code----------------------------------

imgray = im2gray(im);
bw = imbinarize(imgray , 0);




BW2 = bwmorph(imcomplement(bw),'thicken',1);

BW2=bwmorph(BW2,'bridge'); 

se = strel('line',3,180);  % Structuring element for dilation
BW2 = imdilate(BW2,se);    




n = ones(75 , 150 , 3); 
imOut = im;

v(: , : , 1 ) = imcomplement(BW2);



R = imOut(: , : , 1);
G = imOut(: , : , 2);
B = imOut(: , : , 3);


R(v(: , : ,1) == 0) = 0;
G(v(: , : ,1) == 0) = 0;
B(v(: , : ,1) == 0) = 255;



imOut(: , : , 1) = R;
imOut(: , : , 2) = G;
imOut(: , : , 3) = B;
imOut = imresize(imOut , [76 150]);


results.imout = imOut;
results.imoutFlipped1 = flip(imOut,2);
results.imoutFlipped2 = flip(imOut,1);
results.imoutFlipped3 = flip(flip(imOut , 2),1);

%--------------------------------------------------------------------------

